# Generated by Django 2.1.2 on 2018-10-22 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('thumbnail', models.ImageField(default='/default/thinking_emoji.png', upload_to='avatars')),
                ('interest_type', models.CharField(choices=[('M', 'Movie'), ('A', 'Anime'), ('B', 'Book'), ('G', 'Games'), ('S', 'Series'), ('O', 'Other')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Interested',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('super_like', models.BooleanField(default=False)),
                ('interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.Interest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='/default/user.png', upload_to='avatars')),
                ('about_me', models.TextField(max_length=280)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='interest',
            name='user_interested',
            field=models.ManyToManyField(through='baseapp.Interested', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='interest',
            unique_together={('name', 'interest_type')},
        ),
    ]
