# Generated by Django 2.1.2 on 2018-10-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interested',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interest',
            name='thumbnail',
            field=models.ImageField(default='/default/thinking_emoji.png', upload_to='interest_images'),
        ),
    ]
