# Generated by Django 2.1.2 on 2018-10-29 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('baseapp', '0002_auto_20181022_1708'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interested',
            options={'ordering': ['-super_like']},
        ),
        migrations.AddField(
            model_name='interest',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='interest',
            name='user_interested',
            field=models.ManyToManyField(blank=True, related_name='interests', through='baseapp.Interested', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='interest',
            unique_together=set(),
        ),
    ]
